### ISSUE TITLE
Used memory percentage for BSD

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#78]
It looks like Linux and Mac report memory differently. I added a check in agent.js to detect Linux or Mac with a different formula. If BSD handles memory differently, please add an if statement for it with the correct formula. If nothing needs to be done, this can be closed.

**Comment by TokinRing** [comment]
Currently FreeBSD has an outdated version of docker, so supporting PiCluster on BSD will be a waste of time until a newer version comes along. Last time I tried to compile docker from source on FreeBSD I was met with a few build errors that prevented a successful build.

I vote to close this issue, at least until a newer version of docker on FreeBSD comes out. I'll keep you posted on any changes. I'm sure if a new version of docker comes out on FreeBSD it will be mentioned on BSDNow.

Also there is no native support for docker on OpenBSD. From the guides I've read, docker is installed on a VM. This may be acceptable for some use cases, but my use case requires bare metal since a VM will cause too much bloat on resources.
